import type { FormEvent } from 'react';
import { useState } from 'react';
import { ArrowLeft, Check, CircleAlert, Info, Landmark, Loader2, ShieldCheck, Sparkles } from 'lucide-react';
import { Link } from 'wouter';
import { getGetMoneyCalendarQueryKey, useCheckAffordability, useGetMoneyCalendar, type AffordabilityResult } from '@workspace/api-client-react';

const money = (value: number) => new Intl.NumberFormat('en-AE', { maximumFractionDigits: 0 }).format(Math.round(value));
const moneyShort = (value: number) => `AED ${money(value)}`;

const initialLoan = { amount: 500000, annualRate: 4.75, tenureMonths: 48, upfrontCash: 60000, financedFee: false };

function Metric({ label, value, hint, good }: { label: string; value: string; hint: string; good?: boolean }) {
  return <div className="rounded-xl border border-border bg-background p-4"><p className="font-mono-data text-[10px] uppercase tracking-[.14em] text-muted-foreground">{label}</p><p className={`mt-2 text-xl font-medium ${good === false ? 'text-destructive' : good ? 'text-[hsl(var(--chart-3))]' : 'text-foreground'}`}>{value}</p><p className="mt-1 text-[11px] text-muted-foreground">{hint}</p></div>;
}

function ResultPanel({ result }: { result: AffordabilityResult }) {
  const tone = result.verdict === 'fits' ? 'bg-[hsl(var(--chart-3)/.1)] text-[hsl(var(--chart-3))]' : result.verdict === 'fits-if' ? 'bg-accent/20 text-primary' : 'bg-[hsl(var(--destructive)/.1)] text-destructive';
  return <section className="reveal rounded-2xl border border-border bg-card p-5 shadow-sm md:p-7" data-testid="section-loan-result">
    <div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-start"><div><span className={`inline-flex items-center gap-2 rounded-full px-3 py-1.5 font-mono-data text-[10px] uppercase tracking-[.12em] ${tone}`}><span className="size-1.5 rounded-full bg-current" />{result.verdict === 'fits-if' ? 'Fits with a condition' : result.verdict === 'fits' ? 'Fits your frame' : 'Not yet'}</span><h2 className="mt-4 max-w-xl font-display text-4xl leading-[.98] text-primary md:text-5xl" data-testid="text-loan-headline">{result.headline}</h2></div><Landmark className="size-8 text-primary/40" /></div>
    <div className="mt-7 grid gap-3 sm:grid-cols-3"><Metric label="Monthly payment" value={moneyShort(result.monthlyInstallment)} hint={`Max suggested ${moneyShort(result.maxInstallment)}`} good={result.monthlyInstallment <= result.maxInstallment} /><Metric label="After upfront cash" value={moneyShort(result.resilience.bufferAfterUpfront)} hint={`Target buffer ${moneyShort(result.resilience.targetBuffer)}`} good={result.resilience.bufferAfterUpfront >= result.resilience.targetBuffer} /><Metric label="Lowest balance" value={moneyShort(result.calendar.lowestBalance)} hint={`In ${result.calendar.worstMonth}`} good={result.calendar.lowestBalance >= 0} /></div>
    <div className="mt-5 grid gap-3 sm:grid-cols-3"><Metric label="Legal debt ratio" value={`${result.legal.debtRatio.toFixed(1)}%`} hint={`Limit ${result.legal.maxDebtRatio.toFixed(1)}%`} good={result.legal.passes} /><Metric label="Salary multiple" value={`${result.legal.salaryMultiple.toFixed(1)}×`} hint={`Limit ${result.legal.maxSalaryMultiple.toFixed(1)}×`} good={result.legal.salaryMultiple <= result.legal.maxSalaryMultiple} /><Metric label="Resilience" value={`${result.resilience.monthsSurvived} months`} hint="Without fresh income" good={result.resilience.monthsSurvived >= 3} /></div>
    {result.suggestions.length > 0 && <div className="mt-6 rounded-xl bg-secondary/60 p-4"><div className="mb-3 flex items-center gap-2 text-sm font-semibold"><Sparkles className="size-4 text-primary" />Ways to make this calmer</div><ul className="space-y-2">{result.suggestions.map((suggestion) => <li key={suggestion} className="flex gap-2 text-xs leading-5 text-muted-foreground"><Check className="mt-0.5 size-3.5 shrink-0 text-primary" />{suggestion}</li>)}</ul></div>}
    <div className="mt-6 border-t border-border pt-4"><p className="flex items-center gap-2 text-xs font-semibold"><Info className="size-3.5 text-primary" />Assumptions</p><ul className="mt-2 grid gap-1 sm:grid-cols-2">{result.assumptions.map((item) => <li key={item} className="text-xs leading-5 text-muted-foreground">· {item}</li>)}</ul></div>
  </section>;
}

export default function LoanPage() {
  const { data: calendar } = useGetMoneyCalendar({ query: { queryKey: getGetMoneyCalendarQueryKey() } });
  const affordability = useCheckAffordability();
  const [form, setForm] = useState(initialLoan);
  const [result, setResult] = useState<AffordabilityResult>();
  const [noForNow, setNoForNow] = useState(false);
  const setField = (key: keyof typeof initialLoan, value: string | boolean) => setForm((current) => ({ ...current, [key]: typeof value === 'boolean' ? value : Number(value) }));
  const submit = (event: FormEvent) => { event.preventDefault(); setNoForNow(false); affordability.mutate({ data: form }, { onSuccess: setResult }); };
  return <div className="space-y-7">
    <div className="reveal flex items-center gap-3"><Link href="/" className="grid size-9 place-items-center rounded-full border border-border bg-card text-muted-foreground transition-colors hover:text-primary" data-testid="link-back-calendar"><ArrowLeft className="size-4" /></Link><div><p className="font-mono-data text-[10px] uppercase tracking-[.16em] text-muted-foreground">Decision 01 / borrowing</p><h1 className="font-display text-4xl leading-none text-primary md:text-5xl">Can I safely borrow?</h1></div></div>
    <div className="grid gap-5 lg:grid-cols-[.85fr_1.15fr]">
      <section className="reveal reveal-delay-1 rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6" data-testid="section-loan-form"><div className="mb-6 flex items-start justify-between"><div><p className="text-sm font-medium">Give it the real numbers.</p><p className="mt-1 text-xs leading-5 text-muted-foreground">We check UAE legal limits, your month-by-month cash flow, and the buffer left after upfront cash.</p></div><div className="grid size-10 place-items-center rounded-xl bg-secondary"><Landmark className="size-5 text-primary" /></div></div>
        <form onSubmit={submit} className="space-y-4">
          <label className="block"><span className="mb-1.5 block text-xs font-semibold">Loan amount <span className="font-normal text-muted-foreground">(AED)</span></span><input value={form.amount} onChange={(e) => setField('amount', e.target.value)} type="number" min="0" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono-data text-sm outline-none ring-primary/30 transition focus:ring-4" data-testid="input-loan-amount" /></label>
          <div className="grid grid-cols-2 gap-3"><label className="block"><span className="mb-1.5 block text-xs font-semibold">Annual rate <span className="font-normal text-muted-foreground">(%)</span></span><input value={form.annualRate} onChange={(e) => setField('annualRate', e.target.value)} type="number" step="0.01" min="0" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono-data text-sm outline-none focus:ring-4 focus:ring-primary/30" data-testid="input-loan-rate" /></label><label className="block"><span className="mb-1.5 block text-xs font-semibold">Tenure <span className="font-normal text-muted-foreground">(months)</span></span><input value={form.tenureMonths} onChange={(e) => setField('tenureMonths', e.target.value)} type="number" min="1" max="120" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono-data text-sm outline-none focus:ring-4 focus:ring-primary/30" data-testid="input-loan-tenure" /></label></div>
          <label className="block"><span className="mb-1.5 block text-xs font-semibold">Upfront cash <span className="font-normal text-muted-foreground">(AED)</span></span><input value={form.upfrontCash} onChange={(e) => setField('upfrontCash', e.target.value)} type="number" min="0" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono-data text-sm outline-none focus:ring-4 focus:ring-primary/30" data-testid="input-upfront-cash" /></label>
          <label className="flex cursor-pointer items-center gap-3 rounded-xl border border-border bg-background p-3.5"><input checked={form.financedFee} onChange={(e) => setField('financedFee', e.target.checked)} type="checkbox" className="size-4 accent-[hsl(var(--primary))]" data-testid="input-financed-fee" /><span className="text-xs text-muted-foreground">Include processing fee in the financed amount</span></label>
          <div className="flex flex-col gap-2 pt-2"><button disabled={affordability.isPending} type="submit" className="flex h-11 items-center justify-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground transition-transform hover:-translate-y-0.5 disabled:opacity-60" data-testid="button-check-affordability">{affordability.isPending ? <Loader2 className="size-4 animate-spin" /> : <ShieldCheck className="size-4" />} Check my affordability</button><button type="button" onClick={() => { setNoForNow(true); setResult(undefined); }} className={`flex h-10 items-center justify-center gap-2 rounded-xl border text-xs font-medium transition-colors ${noForNow ? 'border-[hsl(var(--chart-3)/.4)] bg-[hsl(var(--chart-3)/.1)] text-[hsl(var(--chart-3))]' : 'border-border text-muted-foreground hover:bg-muted'}`} data-testid="button-loan-do-nothing">{noForNow && <Check className="size-3.5" />} Do nothing for now</button></div>
          {affordability.isError && <p className="flex gap-2 text-xs text-destructive" data-testid="status-affordability-error"><CircleAlert className="size-4 shrink-0" />The check didn't complete. Review the numbers and try again.</p>}
        </form>
        {calendar && <p className="mt-5 border-t border-border pt-4 text-[11px] leading-5 text-muted-foreground"><span className="font-semibold text-foreground">Using {calendar.monthLabel}.</span> This decision will be read against your seeded salary and cash-flow calendar.</p>}
      </section>
      <div className="reveal reveal-delay-2">{result ? <ResultPanel result={result} /> : <div className="flex min-h-[440px] flex-col justify-between rounded-2xl border border-dashed border-border bg-card/60 p-6" data-testid="empty-loan-result"><div><div className="mb-5 grid size-12 place-items-center rounded-2xl bg-secondary"><ShieldCheck className="size-6 text-primary" /></div><h2 className="font-display text-4xl leading-[.98] text-primary">No pressure.<br /><em>Just a clearer next step.</em></h2><p className="mt-4 max-w-sm text-sm leading-6 text-muted-foreground">The answer is not a bank's maximum. It is the commitment your actual month can carry and your future self can live with.</p></div><div className="flex items-start gap-3 border-t border-border pt-5 text-xs leading-5 text-muted-foreground"><Info className="mt-0.5 size-4 shrink-0 text-primary" /><span>Do nothing is always a valid outcome. A pause can be part of the plan.</span></div></div>}</div>
    </div>
  </div>;
}
