import { useEffect, useMemo, useState } from 'react';
import { ArrowDownLeft, ArrowUpRight, Bell, BookOpen, CalendarDays, ChevronRight, CircleHelp, Home, Landmark, Plus, ShieldCheck, Sparkles, Target, X } from 'lucide-react';
import { Link } from 'wouter';
import { getGetMoneyCalendarQueryKey, useGetMoneyCalendar, type MoneyCalendar } from '@workspace/api-client-react';

const money = (value: number) => new Intl.NumberFormat('en-AE', { maximumFractionDigits: 0 }).format(Math.round(value));

function EventRow({ event }: { event: MoneyCalendar['events'][number] }) {
  const income = event.kind === 'income';
  const tone = income ? '#12A66A' : event.kind === 'goal' ? '#139BE8' : '#D20A58';
  return <div className="group flex items-center gap-3.5 border-b border-[#E4E7EC] py-3.5 last:border-0" data-testid={`row-event-${event.id}`}>
    <div className="w-[34px] shrink-0 text-center"><p className="text-[9px] font-semibold tracking-[.12em] text-[#98A2B3]">{String(event.day).padStart(2, '0')}</p><p className="mt-0.5 text-[19px] font-semibold leading-none text-[#003B73]">{event.day}</p></div>
    <div className="relative flex h-[34px] w-[10px] shrink-0 items-center justify-center"><span className="absolute h-full w-px bg-[#E4E7EC] group-last:h-0" /><span className="relative size-2.5 rounded-full border-2 border-white" style={{ backgroundColor: tone }} /></div>
    <div className="min-w-0 flex-1"><p className="truncate text-[13px] font-semibold text-[#17212B]">{event.label}</p>{event.note && <p className="mt-0.5 truncate text-[10px] text-[#667085]">{event.note}</p>}</div>
    <span className={`whitespace-nowrap rounded-full px-2 py-1 text-[10px] font-semibold ${income ? 'bg-[#F2F4F7] text-[#12A66A]' : 'bg-[#FCEAF1] text-[#D20A58]'}`}>AED {income ? '+' : '−'}{money(event.amount)}</span>
  </div>;
}

function BayzatiLogo() {
  return <div className="flex items-center gap-2"><img src="/images/bayzati-logo.png" alt="Bayzati" className="size-9 object-contain" data-testid="img-bayzati-logo" /><div className="leading-none"><p className="text-[19px] font-semibold tracking-[-.04em] text-[#003B73]">bayzati</p><p className="mt-1 text-[9px] font-semibold uppercase tracking-[.13em] text-[#98A2B3]">your calmer money plan</p></div></div>;
}

export default function MoneyCalendarPage() {
  const { data: calendar, isLoading, isError, refetch } = useGetMoneyCalendar({ query: { queryKey: getGetMoneyCalendarQueryKey() } });
  const [sheetOpen, setSheetOpen] = useState(false);
  const [assistantOpen, setAssistantOpen] = useState(false);
  const [entryType, setEntryType] = useState<'income' | 'commitment'>('commitment');
  const [saved, setSaved] = useState(false);
  const [entryName, setEntryName] = useState('');
  const [entryAmount, setEntryAmount] = useState('');
  const [entryDay, setEntryDay] = useState('');
  useEffect(() => { const close = (event: KeyboardEvent) => { if (event.key === 'Escape') { setSheetOpen(false); setAssistantOpen(false); } }; window.addEventListener('keydown', close); return () => window.removeEventListener('keydown', close); }, []);
  const events = useMemo(() => [...(calendar?.events ?? [])].sort((a, b) => a.day - b.day), [calendar?.events]);
  if (isLoading) return <div className="mx-auto max-w-[390px] space-y-5 bg-[#F8FAFC] p-5" data-testid="loading-calendar"><div className="h-40 animate-pulse rounded-[18px] bg-[#E4E7EC]" /><div className="h-72 animate-pulse rounded-[18px] bg-[#E4E7EC]" /></div>;
  if (isError || !calendar) return <div className="mx-auto max-w-md rounded-[18px] border border-[#D20A58]/25 bg-white p-8 text-center" data-testid="error-calendar"><CircleHelp className="mx-auto mb-3 size-8 text-[#D20A58]" /><h1 className="text-2xl font-bold text-[#003B73]">The calendar is taking a breath.</h1><p className="mt-2 text-sm text-[#667085]">We could not load your month. Your decisions are still safe.</p><button onClick={() => refetch()} className="mt-5 rounded-xl bg-[#003B73] px-4 py-3 text-sm font-semibold text-white" data-testid="button-retry-calendar">Try again</button></div>;
  const incomeTotal = (calendar.income?.basic ?? 0) + (calendar.income?.housingAllowance ?? 0) + (calendar.income?.variable ?? 0);
  const largePayment = events.filter((event) => event.kind !== 'income').sort((a, b) => b.amount - a.amount)[0];
  const monthAbbreviation = calendar.monthLabel.split(' ')[0]?.slice(0, 3) ?? '';
  const openSheet = () => { setSaved(false); setSheetOpen(true); };
  return <main className="relative mx-auto min-h-[100dvh] w-full max-w-[520px] overflow-x-hidden bg-[#F8FAFC] font-['Inter',system-ui,sans-serif] text-[#17212B] shadow-[0_0_40px_rgba(0,46,93,.06)]" data-testid="page-money-calendar">
    <div className="pointer-events-none absolute -right-24 -top-24 size-64 rounded-full bg-[#EAF6FD] opacity-70" />
    <div className="relative px-5 pb-40 pt-6">
      <header className="flex items-center justify-between"><BayzatiLogo /><div className="flex items-center gap-2"><button aria-label="Notifications" onClick={() => setAssistantOpen(true)} className="grid size-11 place-items-center rounded-full border border-[#E4E7EC] bg-white text-[#667085]" data-testid="button-notifications"><Bell size={17} /></button><button aria-label="Open profile" onClick={() => setAssistantOpen(true)} className="grid size-11 place-items-center rounded-full bg-[#EAF6FD] text-[11px] font-semibold text-[#003B73]" data-testid="button-profile">MA</button></div></header>
      <section className="mt-7 flex items-end justify-between gap-3"><div><p className="text-[11px] font-semibold uppercase tracking-[.16em] text-[#667085]">Money calendar</p><h1 className="mt-1 text-[28px] font-bold leading-none tracking-[-.04em] text-[#003B73]" data-testid="text-month-label">{calendar.monthLabel}</h1></div><button onClick={() => setAssistantOpen(true)} className="flex min-h-11 items-center gap-1 rounded-full border border-[#E4E7EC] bg-white px-3 py-2 text-[10px] font-semibold text-[#003B73]" data-testid="button-this-month"><CalendarDays size={14} /> This month</button></section>
      <section className="mt-5 overflow-hidden rounded-[18px] bg-[#003B73] px-5 py-5 text-white" data-testid="card-safe-to-spend"><div className="flex items-center justify-between"><p className="flex items-center gap-1.5 text-[10px] font-semibold uppercase tracking-[.13em] text-[#EAF6FD]"><ShieldCheck size={14} className="text-[#139BE8]" /> Safe to spend</p><button aria-label="What is safe to spend?" onClick={() => setAssistantOpen(true)} className="text-[#EAF6FD]" data-testid="button-safe-to-spend-help"><CircleHelp size={15} /></button></div><p className="mt-3 text-[36px] font-bold tabular-nums tracking-[-.07em]" data-testid="text-safe-to-spend">AED {money(calendar.safeToSpend)}</p><p className="mt-1.5 text-[12px] leading-5 text-[#EAF6FD]">Available after known commitments, with AED {money(calendar.bufferTarget)} breathing room.</p><div className="mt-5 flex items-end justify-between gap-4 border-t border-white/15 pt-4"><div className="min-w-0"><p className="text-[10px] text-[#98A2B3]">Next large payment</p><p className="mt-1 truncate text-[13px] font-semibold">{largePayment ? `${largePayment.label} · ${largePayment.day} ${monthAbbreviation}` : 'Nothing scheduled'}</p></div>{largePayment && <p className="shrink-0 text-[12px] font-semibold text-[#D20A58]">AED {money(largePayment.amount)}</p>}</div><div className="mt-3 h-1.5 overflow-hidden rounded-full bg-white/15"><div className="h-full rounded-full bg-[#139BE8]" style={{ width: `${Math.min(100, Math.max(8, calendar.safeToSpend / Math.max(incomeTotal, 1) * 100))}%` }} /></div><p className="mt-2 text-[10px] text-[#EAF6FD]">Projected payday on the {calendar.projectedPayday}th · tight day {calendar.tightDay}</p></section>
      <div className="mt-4 flex items-center gap-2 rounded-[18px] border border-[#D20A58]/25 bg-[#FCEAF1] px-3.5 py-3" data-testid="status-tight-day"><span className="grid size-7 shrink-0 place-items-center rounded-full bg-white text-[#D20A58]"><Sparkles size={14} /></span><p className="text-[11px] leading-4 text-[#667085]"><span className="font-semibold text-[#D20A58]">A gentle heads-up:</span> cash feels tight around the {calendar.tightDay}th. Keep your buffer untouched.</p></div>
      <section className="mt-5 rounded-[18px] border border-[#E4E7EC] bg-white px-4 py-3" data-testid="section-coming-up"><div className="flex items-center justify-between pb-1"><h2 className="text-[19px] font-bold text-[#003B73]">Coming up</h2><button onClick={openSheet} className="flex min-h-11 items-center gap-1 text-[10px] font-semibold text-[#139BE8]" data-testid="button-see-all-events">See all <ChevronRight size={13} /></button></div>{events.length ? events.map((event) => <EventRow key={event.id} event={event} />) : <p className="px-2 py-8 text-center text-sm text-[#667085]" data-testid="empty-calendar">A quiet month ahead.</p>}</section>
      <section className="mt-5 border-t border-[#E4E7EC] pt-4" data-testid="section-assumptions"><p className="flex items-center gap-2 text-xs font-semibold text-[#17212B]"><CircleHelp className="size-4 text-[#139BE8]" /> What this view assumes</p><div className="mt-3 space-y-2">{calendar.assumptions.map((assumption, index) => <p key={assumption} className="text-xs text-[#667085]"><span className="mr-2 font-semibold text-[#003B73]">0{index + 1}</span>{assumption}</p>)}</div></section>
    </div>
    <div className="pointer-events-none fixed inset-x-0 bottom-[106px] z-20 mx-auto flex max-w-[520px] justify-end px-5"><button onClick={openSheet} className="pointer-events-auto flex min-h-11 items-center gap-2 rounded-full bg-[#D20A58] px-4 py-3 text-[12px] font-semibold text-white shadow-lg" data-testid="button-add-to-calendar"><Plus size={17} /> Add to calendar</button></div>
     <div className="fixed inset-x-4 bottom-4 z-20 mx-auto flex max-w-[488px] items-center gap-2"><nav className="flex h-[70px] flex-1 items-center justify-around rounded-full border border-[#E4E7EC] bg-white px-1 shadow-[0_2px_8px_rgba(0,46,93,.05)]" aria-label="Bayzati navigation">{[['/home', 'Home', Home], ['/', 'Plan', Landmark], ['/goals', 'Goals', Target], ['/learn', 'Learn', BookOpen]].map(([href, label, Icon]) => <Link key={label as string} href={href as string} className={`flex h-[60px] min-w-0 flex-1 flex-col items-center justify-center gap-1 rounded-full ${label === 'Plan' ? 'bg-[#EAF6FD] text-[#003B73]' : 'text-[#667085]'}`} data-testid={`link-nav-${(label as string).toLowerCase()}`}><Icon size={20} /><span className="text-[10px] font-semibold">{label as string}</span></Link>)}</nav><button aria-label="Open Bayzati assistant" onClick={() => setAssistantOpen(true)} className="grid size-[66px] shrink-0 place-items-center rounded-full border border-[#d8e0e9] bg-white shadow-lg" data-testid="button-open-assistant"><span className="relative grid size-[58px] place-items-center rounded-full border border-[#E4E7EC] text-[#003B73]"><Sparkles size={19} /><i className="absolute right-[13px] top-[11px] size-1.5 rounded-full bg-[#D20A58]" /></span></button></div>
    {sheetOpen && <div className="fixed inset-0 z-30 bg-[#092e59]/45" onClick={() => setSheetOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="add-title" onClick={(e) => e.stopPropagation()} className="absolute inset-x-0 bottom-0 mx-auto max-w-[520px] rounded-t-[24px] bg-white px-5 pb-7 pt-5"><div className="mx-auto mb-5 h-1 w-10 rounded-full bg-[#E4E7EC]" /><div className="flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#667085]">Local-only update</p><h2 id="add-title" className="mt-1 text-[25px] font-bold text-[#003B73]">Add something new</h2></div><button aria-label="Close add to calendar" onClick={() => setSheetOpen(false)} className="grid size-11 place-items-center rounded-full border border-[#E4E7EC]" data-testid="button-close-sheet"><X size={16} /></button></div><div className="mt-5 flex rounded-full bg-[#F2F4F7] p-1 text-[12px] font-semibold"><button onClick={() => setEntryType('income')} className={`min-h-11 flex-1 rounded-full ${entryType === 'income' ? 'bg-white text-[#003B73]' : 'text-[#667085]'}`} data-testid="button-entry-income"><ArrowDownLeft className="mr-1 inline size-3.5 text-[#12A66A]" />Income</button><button onClick={() => setEntryType('commitment')} className={`min-h-11 flex-1 rounded-full ${entryType === 'commitment' ? 'bg-white text-[#003B73]' : 'text-[#667085]'}`} data-testid="button-entry-commitment"><ArrowUpRight className="mr-1 inline size-3.5 text-[#D20A58]" />Commitment</button></div><label className="mt-5 block text-[11px] font-semibold text-[#667085]">What should we call it?<input value={entryName} onChange={(e) => setEntryName(e.target.value)} placeholder="e.g. Salary" className="mt-1.5 w-full rounded-xl border border-[#E4E7EC] px-3.5 py-3 text-[13px] outline-none focus:border-[#139BE8]" data-testid="input-entry-name" /></label><div className="mt-3 flex gap-3"><label className="flex-1 text-[11px] font-semibold text-[#667085]">Amount<input value={entryAmount} onChange={(e) => setEntryAmount(e.target.value)} placeholder="AED 0" className="mt-1.5 w-full rounded-xl border border-[#E4E7EC] px-3.5 py-3 text-[13px] outline-none" data-testid="input-entry-amount" /></label><label className="w-[108px] text-[11px] font-semibold text-[#667085]">Day<input value={entryDay} onChange={(e) => setEntryDay(e.target.value)} placeholder="27" className="mt-1.5 w-full rounded-xl border border-[#E4E7EC] px-3.5 py-3 text-[13px] outline-none" data-testid="input-entry-day" /></label></div><button onClick={() => { setSaved(true); setTimeout(() => setSheetOpen(false), 700); }} className="mt-5 min-h-11 w-full rounded-xl bg-[#003B73] py-3.5 text-[13px] font-semibold text-white" data-testid="button-save-entry">{saved ? 'Saved locally' : 'Save locally'}</button><p className="mt-3 text-center text-[10px] text-[#98A2B3]">No network call is made; this preview does not change your API calendar.</p></section></div>}
    {assistantOpen && <div className="fixed inset-0 z-40 bg-[#092e59]/25" onClick={() => setAssistantOpen(false)}><section role="dialog" aria-modal="true" aria-labelledby="assistant-title" onClick={(e) => e.stopPropagation()} className="absolute inset-x-4 bottom-28 mx-auto max-w-[488px] rounded-[18px] border border-[#E4E7EC] bg-white px-4 py-4 shadow-lg"><div className="flex items-start justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[.14em] text-[#D20A58]">Bayzati assistant</p><h2 id="assistant-title" className="mt-1 text-[21px] font-bold text-[#003B73]">A calmer money moment.</h2></div><button aria-label="Close assistant" onClick={() => setAssistantOpen(false)} className="grid size-11 place-items-center rounded-full border border-[#E4E7EC]" data-testid="button-close-assistant"><X size={15} /></button></div><p className="mt-4 rounded-[15px] bg-[#EAF6FD] px-3.5 py-3 text-[12px] font-semibold leading-5 text-[#003B73]">“What can I safely spend this week?”<span className="mt-1 block text-[10px] font-normal text-[#667085]">Ask about your plan or upcoming commitments. Assistant answers are local-only for now.</span></p></section></div>}
  </main>;
}