import { useState } from "react";
import {
  ArrowUpRight, BarChart3, CalendarDays, Check, ChevronRight, CloudSun,
  Home, Info, Landmark, ShieldCheck,
} from "lucide-react";
import "./_group.css";

const money = (value: number) => new Intl.NumberFormat("en-AE", { maximumFractionDigits: 0 }).format(value);
const moneyShort = (value: number) => `AED ${money(value)}`;

const events = [
  { id: "salary", day: 1, kind: "income", label: "Salary", note: "Basic + housing allowance", amount: 29400 },
  { id: "rent", day: 3, kind: "fixed", label: "Apartment rent", note: "Jumeirah · monthly commitment", amount: 7600 },
  { id: "school", day: 8, kind: "fixed", label: "School fees", note: "Term 1 instalment", amount: 4200 },
  { id: "card", day: 12, kind: "fixed", label: "Credit card", note: "Statement payment", amount: 1850 },
  { id: "travel", day: 18, kind: "lump", label: "Family flights", note: "Booked for October", amount: 3200 },
  { id: "buffer", day: 25, kind: "goal", label: "Emergency buffer", note: "Monthly top-up", amount: 1500 },
];

const kindStyles: Record<string, string> = {
  income: "bg-[hsl(var(--chart-3)/.16)] text-[hsl(var(--chart-3))]",
  fixed: "bg-[hsl(var(--chart-4)/.13)] text-[hsl(var(--chart-4))]",
  lump: "bg-[hsl(var(--chart-2)/.18)] text-primary",
  goal: "bg-secondary text-primary",
};

function Sidebar() {
  const items = [
    { label: "Money calendar", icon: CalendarDays, active: true },
    { label: "Can I borrow?", icon: Landmark },
    { label: "Rent or buy?", icon: Home },
  ];
  return <aside className="fixed inset-y-0 left-0 z-40 hidden w-[252px] flex-col bg-sidebar px-5 py-6 text-sidebar-foreground md:flex">
    <div className="mb-12 flex items-center gap-3"><span className="grid size-10 place-items-center rounded-[13px] bg-sidebar-primary text-sidebar-primary-foreground shadow-sm"><span className="font-display text-2xl leading-none">M</span></span><span><span className="block font-display text-[25px] leading-none tracking-tight">Money Calendar</span><span className="mt-1 block font-mono-data text-[9px] uppercase tracking-[.18em] text-sidebar-foreground/55">A calmer yes</span></span></div>
    <nav className="space-y-1"><p className="mb-3 px-3 font-mono-data text-[10px] uppercase tracking-[.18em] text-sidebar-foreground/45">Your decisions</p>{items.map(({ label, icon: Icon, active }) => <div key={label} className={`group flex items-center gap-3 rounded-xl px-3 py-3 text-sm ${active ? "bg-sidebar-accent text-sidebar-accent-foreground" : "text-sidebar-foreground/65"}`}><Icon className={`size-[17px] ${active ? "text-sidebar-primary" : "text-sidebar-foreground/45"}`} strokeWidth={1.8} /><span>{label}</span>{active && <ChevronRight className="ml-auto size-4 text-sidebar-primary" />}</div>)}</nav>
    <div className="mt-auto rounded-2xl border border-sidebar-border bg-sidebar-accent/60 p-4"><div className="mb-3 flex items-center gap-2 text-sidebar-primary"><ShieldCheck className="size-4" /><span className="font-mono-data text-[10px] uppercase tracking-[.16em]">Private by design</span></div><p className="text-xs leading-5 text-sidebar-foreground/65">A decision lens for your salary, commitments, and the months between them.</p></div>
    <div className="mt-5 flex items-center gap-3 border-t border-sidebar-border pt-5"><span className="grid size-9 place-items-center rounded-full bg-sidebar-primary/15 font-mono-data text-xs text-sidebar-primary">MA</span><div><p className="text-sm">Mariam Al Noor</p><p className="text-[11px] text-sidebar-foreground/45">Dubai · AED</p></div></div>
  </aside>;
}

function EventRow({ event }: { event: typeof events[number] }) {
  return <div className="flex items-center gap-4 border-b border-border/70 py-3.5 last:border-0"><div className="w-8 text-center"><span className="font-mono-data text-[11px] text-muted-foreground">DAY</span><span className="mt-0.5 block text-lg leading-none">{event.day}</span></div><div className={`size-2 shrink-0 rounded-full ${event.kind === "income" ? "bg-[hsl(var(--chart-3))]" : event.kind === "goal" ? "bg-accent" : "bg-[hsl(var(--chart-4))]"}`} /><div className="min-w-0 flex-1"><p className="truncate text-sm font-medium">{event.label}</p><p className="mt-0.5 truncate text-xs text-muted-foreground">{event.note}</p></div><span className={`rounded-full px-2 py-1 font-mono-data text-[10px] ${kindStyles[event.kind]}`}>{event.kind === "income" ? "+" : "−"}{money(event.amount)}</span></div>;
}

export function Current() {
  const [stayingPut, setStayingPut] = useState(false);
  const [checked, setChecked] = useState(false);
  const income = 29400;
  return <div className="money-calendar-current page-grain min-h-screen bg-background text-foreground">
    <Sidebar />
    <div className="md:pl-[252px]"><header className="sticky top-0 z-30 flex h-[68px] items-center justify-between border-b border-border/75 bg-background/90 px-5 backdrop-blur-md md:px-10"><div className="flex items-center gap-3 md:hidden"><span className="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground font-display text-lg">M</span><span className="font-display text-xl">Money Calendar</span></div><div className="hidden items-center gap-2 text-xs text-muted-foreground md:flex"><BarChart3 className="size-4 text-primary" />One view for the money decisions that matter.</div><div className="flex items-center gap-3"><span className="hidden rounded-full border border-border bg-card px-3 py-1.5 font-mono-data text-[10px] uppercase tracking-[.12em] text-muted-foreground sm:inline-flex">Dubai · AED</span><span className="size-2 rounded-full bg-[hsl(var(--chart-3))]" /></div></header>
      <main className="mx-auto max-w-[1320px] space-y-7 px-5 py-8 pb-24 md:px-10 md:py-10">
        <section className="flex flex-col justify-between gap-5 sm:flex-row sm:items-end"><div><div className="mb-3 flex items-center gap-2 text-xs text-muted-foreground"><span className="size-1.5 rounded-full bg-[hsl(var(--chart-3))]" />Mariam Al Noor<span className="text-border">/</span>September 2025</div><h1 className="font-display text-5xl leading-[.95] tracking-tight text-primary md:text-6xl">Your month,<br /><em className="text-foreground">made legible.</em></h1><p className="mt-4 max-w-lg text-sm leading-6 text-muted-foreground">The amount you can spend with a clear head, after life has taken its share.</p></div><div className="flex items-center gap-2 text-xs text-muted-foreground"><span className="text-primary">◷</span>Payday projected on the 1st</div></section>
        <section className="overflow-hidden rounded-3xl bg-primary text-primary-foreground shadow-lg"><div className="relative grid gap-8 p-6 md:grid-cols-[1.1fr_.9fr] md:p-9"><div className="absolute -right-20 -top-28 size-80 rounded-full border border-primary-foreground/10" /><div className="absolute -right-4 -top-12 size-52 rounded-full border border-primary-foreground/10" /><div className="relative"><div className="mb-10 flex items-center gap-2 text-[11px] uppercase tracking-[.17em] text-primary-foreground/60"><span className="size-2 rounded-full bg-accent" />Safe to spend</div><p className="font-mono-data text-5xl tracking-[-.07em] md:text-7xl">AED {money(11050)}</p><p className="mt-3 max-w-sm text-sm leading-5 text-primary-foreground/70">Available after your known commitments, with a {moneyShort(6000)} breathing room.</p></div><div className="relative grid grid-cols-2 gap-3 self-end md:pb-1"><div className="rounded-2xl border border-primary-foreground/15 bg-primary-foreground/10 p-4"><p className="font-mono-data text-[10px] uppercase tracking-[.13em] text-primary-foreground/55">Tightest day</p><p className="mt-2 text-2xl font-medium">Day 3</p><p className="mt-1 text-xs text-primary-foreground/60">Keep a little space here</p></div><div className="rounded-2xl border border-primary-foreground/15 bg-primary-foreground/10 p-4"><p className="font-mono-data text-[10px] uppercase tracking-[.13em] text-primary-foreground/55">Monthly income</p><p className="mt-2 text-2xl font-medium">{moneyShort(income)}</p><p className="mt-1 text-xs text-primary-foreground/60">Before commitments</p></div></div></div></section>
        <div className="grid gap-5 lg:grid-cols-[1.25fr_.75fr]"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm md:p-6"><div className="mb-4 flex items-start justify-between"><div><p className="font-mono-data text-[10px] uppercase tracking-[.16em] text-muted-foreground">Cash-flow map</p><h2 className="mt-1 font-display text-3xl">The shape of September 2025</h2></div><span className="rounded-full bg-secondary px-2.5 py-1 font-mono-data text-[10px] text-primary">{events.length} signals</span></div><div className="calendar-grid mb-4 grid grid-cols-7 overflow-hidden rounded-xl border border-border/60 bg-background/50 px-2 py-2 text-center font-mono-data text-[9px] uppercase tracking-[.12em] text-muted-foreground">{["01","05","10","15","20","25","30"].map(day => <span key={day}>{day}</span>)}</div>{events.map(event => <EventRow key={event.id} event={event} />)}</section>
          <div className="space-y-5"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="mb-5 flex items-center justify-between"><div><p className="font-mono-data text-[10px] uppercase tracking-[.16em] text-muted-foreground">Your next question</p><h2 className="mt-1 font-display text-2xl">Name the decision.</h2></div><ArrowUpRight className="size-5 text-primary" /></div><div className="space-y-2">{[["Can I safely borrow?","Run the legal + calendar lens"],["Rent or buy?","See what your horizon can carry"]].map(([title, sub]) => <button key={title} className="soft-lift flex w-full items-center justify-between rounded-xl border border-border bg-background px-4 py-3.5 text-left"><span><span className="block text-sm font-medium">{title}</span><span className="mt-0.5 block text-xs text-muted-foreground">{sub}</span></span><ArrowUpRight className="size-4 text-primary" /></button>)}</div><button onClick={() => setStayingPut(!stayingPut)} className={`mt-3 flex w-full items-center justify-center gap-2 rounded-xl border px-4 py-3 text-sm ${stayingPut ? "border-[hsl(var(--chart-3)/.45)] bg-[hsl(var(--chart-3)/.1)] text-[hsl(var(--chart-3))]" : "border-border text-muted-foreground"}`}>{stayingPut ? <Check className="size-4" /> : <Info className="size-4" />}{stayingPut ? "A clear no is still a decision." : "Do nothing for now"}</button></section>
            <section className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-primary"><ShieldCheck className="size-4" /><span className="font-mono-data text-[10px] uppercase tracking-[.16em]">Quiet confidence check</span></div><h2 className="font-display text-2xl">What if income pauses?</h2><p className="mt-1 max-w-sm text-xs leading-5 text-muted-foreground">A small reality check before a big commitment. Three months without salary, plus a rate bump.</p></div><div className="hidden size-12 place-items-center rounded-full bg-secondary sm:grid"><CloudSun className="size-5 text-primary" /></div></div>{checked ? <div className="mt-5 rounded-xl bg-secondary/60 p-4"><p className="text-sm font-medium">Your essentials stay covered with room to breathe.</p><div className="mt-3 grid grid-cols-3 gap-3"><div><p className="font-mono-data text-lg text-primary">4.2</p><p className="text-[10px] text-muted-foreground">months covered</p></div><div><p className="font-mono-data text-lg text-primary">AED 15,220</p><p className="text-[10px] text-muted-foreground">stressed monthly</p></div><div><p className="font-mono-data text-lg text-primary">AED 8,450</p><p className="text-[10px] text-muted-foreground">ending buffer</p></div></div></div> : <button onClick={() => setChecked(true)} className="mt-5 inline-flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><ShieldCheck className="size-4" />Run the quiet check</button>}</section></div></div>
        <section className="border-t border-border pt-5"><div className="flex items-center gap-2 text-xs font-semibold"><Info className="size-4 text-primary" />What this view assumes</div><div className="mt-3 flex flex-wrap gap-x-6 gap-y-2"><p className="text-xs text-muted-foreground"><span className="mr-2 font-mono-data text-primary">01</span>Salary arrives on the 1st business day</p><p className="text-xs text-muted-foreground"><span className="mr-2 font-mono-data text-primary">02</span>Known commitments stay within their usual range</p><p className="text-xs text-muted-foreground"><span className="mr-2 font-mono-data text-primary">03</span>Emergency buffer remains untouched</p></div></section>
      </main></div>
    <nav className="fixed inset-x-3 bottom-3 z-40 flex items-center justify-around rounded-2xl border border-border/80 bg-card/95 p-2 shadow-lg backdrop-blur-md md:hidden">{[["Calendar",CalendarDays],["Borrow",Landmark],["Home",Home]].map(([label, Icon]) => <div key={label as string} className="flex min-w-0 flex-1 flex-col items-center gap-1 rounded-xl bg-secondary px-2 py-2 text-[10px] text-primary"><Icon className="size-4" /><span>{label as string}</span></div>)}</nav>
  </div>;
}